### ISSUE TITLE
Ok real funny

### ISSUE THREAD

**Issue by Helvariors** [AlexModGuy/Citadel#111]
Right, so could you maybe not destroy my ears and break my game with your uncancellable rickroll video, like i get it, its suuuper funny but i would like to play the game please

**Comment by Slipperyeire07** [comment]
yea, the devs were extremely stupid with this. there is a temp fix but it will reset after a relaunch. go into your mc instance and delete the citadel folder that contains 'video cache'

**Comment by Helvariors** [comment]
Yea i already found about the video cache, but it's still annoying, still thanks!

**Comment by michaellindman** [comment]
if anyone is having trouble getting around this the file for the video is pulled from the domain `ia801602.us.archive.org` so blocking outbound connections to that with either your computer or router will stop it from downloading and playing. This was the only way I could play again without my client crashing due to this.

**Comment by AlexModGuy** [comment]
adding a config right now for this. sorry for the trouble caused, truly.
