### ISSUE TITLE
Newest update virus was detected

### ISSUE THREAD

**Issue by vinnyg0621** [AlexModGuy/Citadel#181]
wait, it wasn't doing this before !?
![Screenshot 2024-07-23 194135](https://github.com/user-attachments/assets/866c6169-92cd-4afe-aba6-61b312e1d254)

help, HELP!!!!!

**Comment by AlexModGuy** [comment]
seems to be an issue with your anti virus software.

**Comment by vinnyg0621** [comment]
yes, it did both of those sites.

**Comment by AlexModGuy** [comment]
very odd, but it's certainly a false flag. the 2.5.6 update was created by running [shadowJar](https://github.com/AlexModGuy/Citadel/blob/master/build.gradle#L189) in the mod's build.gradle. The only new file this update introduced was just [a new mixin to streamline surfaceRule merging](https://github.com/AlexModGuy/Citadel/blob/86523171f6fd4fd3d72161c4717004133398f511/src/main/java/com/github/alexthe666/citadel/mixin/NoiseGeneratorSettingsMixin.java), so that's unlikely to be the cause of this. I'll write this off as just something in common antivirus likely flagging the specified jar name and version as a virus for some unknown reason, but if it persists beyond this version then we certainly will have a problem. For now, none of my mods require 2.5.6, so you can either use it and enjoy the new bugfixes or continue using 2.5.4.
